version: "3.9"
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    volumes:
      - ${LIBRARY}:/audiobooks
      - ${PODCASTS}:/podcasts
      - /portainer/apps/audiobookshelf/config:/config
      - /portainer/apps/audiobookshelf/metadata:/metadata
    ports:
      - ${PORT}:80
    restart: unless-stopped
