version: "3.9"
services:
  calibre-web:
    image: linuxserver/calibre-web
    container_name: calibre-web
    environment:
      - PUID=${PUID} # 1000
      - PGID=${PGID} # 1000
      - TZ=${TZ} # Etc/UTC
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /portainer/apps/calibre-web/config:/config
      - ${LIBRARY}:/books
    ports:
      - ${PORT}:8083
    restart: unless-stopped
