version: "3.9"
services:
  kavita:
    image: b4bz/homer:latest
    container_name: homer
    volumes:
      - /portainer/apps/homer/config:/www/assets
    ports:
      - ${PORT}:8080
    restart: unless-stopped

