version: "3.9"
services:
  kavita:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    volumes:
      - ${SERIES}:/data/series
      - ${MOVIES}:/data/movies
      - /portainer/Files/AppData/Config/Jellyfin:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8096:8096/tcp
      - 8920:8920/tcp
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    volumes:
      - ${MOVIES}:/movies
      - /portainer/Files/AppData/Config/Radarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 7878:7878/tcp
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    volumes:
      - ${SERIES}:/movies
      - /portainer/Files/AppData/Config/Sonarr:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 8989:8989/tcp
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    volumes:
      - /media/torrents:/downloads
      - /portainer/Files/AppData/Config/Jackett:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true
    ports:
      - 9117:9117
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8091
    volumes:
      - /portainer/Files/AppData/Config/Qbittorrent:/config
      - /media:/downloads
    ports:
      - 8091:8091
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
