version: '3.9'
services:
  stump:
    image: aaronleopold/stump
    container_name: stump
    # Replace my paths (prior to the colons) with your own
    volumes:
      - /portainer/Files/AppData/Config/Stump/Config:/config
      - ${LIBRARY}:/data
    ports:
      - ${PORT}:10801
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
